# Generated by Django 4.0.2 on 2022-02-10 06:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='WasteCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('battery', 0), ('biological', 1), ('brown_glass', 2), ('cardboard', 3), ('clothes', 4), ('green_class', 5), ('metal', 6), ('paper', 7), ('plastic', 8), ('trash', 9), ('white_glass', 10)], max_length=50)),
                ('desc', models.CharField(blank=True, max_length=1024, null=True)),
                ('recyclable', models.BooleanField(default=False)),
                ('area', models.CharField(choices=[('Ajax', 0), ('Aurora', 1), ('Brampton', 2), ('Brock', 3), ('Burlington', 4), ('Caledon', 5), ('Clarington', 6), ('East_Gwillimbury', 7), ('Georgina', 8), ('Halton_Hills', 9), ('King', 10), ('Markham', 11), ('Milton', 12), ('Mississauga', 13), ('Newmarket', 14), ('Oakville', 15), ('Oshawa', 16), ('Pickering', 17), ('Richmond_Hill', 18), ('Scugog', 19), ('Toronto', 20), ('Uxbridge', 21), ('Vaughan', 22), ('Whitby', 23), ('Whitchurch_Stouffville', 24)], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=255)),
                ('instructions', models.TextField(blank=True, null=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='internal.wastecategory')),
            ],
        ),
    ]
